import pandas as pd
from datetime import timedelta
#import numpy as np

csvdata='test_sort.csv'  # Use file generated by "test.sh"
#csvdata='temp.txt'

# Read data from CSV file
df = pd.read_csv(csvdata, names=("orid", "dateid", "date_time", "hashid", "card_id", "inst"), header=None, parse_dates=[2])
df = df.set_index("date_time", drop=False)

print(df)

orids = sorted(df["orid"].unique())    # Make a list of patients

for i in range(len(orids)):  # Process each patient individually
    print()
    print("[" + orids[i] + "]")

    task = df[df['orid'] == orids[i]].copy()               # Extract one patient from whole data.
    task.sort_index(ascending=True ,inplace=True)          # Sort data by date
    task['t-shift'] = task['date_time'].shift(-1)          # Add temporal column to calc time delta
    task['tdiff'] = (task['t-shift'] - task['date_time'])  # Calc time delta
    task = task[task['tdiff'] >= timedelta(days=180)]      # Check 180 days, extract available data
    task = task.drop('t-shift', axis=1)                    # Remove temporal column
    serial_num = pd.RangeIndex(start=1, stop=len(task.index) + 1, step=1)  # Count number of available data
    task['No'] = serial_num.astype("str").str.zfill(2)     # Add "No." column
    task['base_name'] = task['orid'].astype("str") + "_" + task["No"] + "_" + task["dateid"].astype("str")  # Add "base_name" column

    print(task)

    # Combine each lists to one
    if i == 0:
        result = task.copy()
    elif i > 0:
        result = pd.concat([result, task])

print(result)

result.to_csv('result.csv', index=False)